---
title: "STAT 221 Homework 1"
author: "John Rapp Farnes | 405461225"
date: "15 januari 2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.3

a)
```{r}
set.seed(2020)

w = rnorm(550,0,1) # 50 extra to avoid startup problems
x = filter(w, filter=c(0,-.9), method="recursive")[-(1:50)] # remove first 50

par(mfrow=c(2, 1))
plot.ts(x, main="Autoregression")

v = filter(w, sides=2, filter=rep(1/4,4)) # moving average
plot.ts(v, main="moving average")
```


b)
```{r}
t = 1:100
x = cos(2*pi * t / 4)

par(mfrow=c(2, 1))
plot.ts(x, main="periodic")

v = rep(0, 100) #filter(x, sides=2, filter=rep(1/4,4)) # moving average
plot.ts(v, main="moving average")
```

c)
```{r}
t = 1:100
x = cos(2*pi * t / 4) + rnorm(100,0,1)

par(mfrow=c(2, 1))
plot.ts(x, main="periodic with noise")

v = filter(x, sides=2, filter=rep(1/4,4)) # moving average
plot.ts(v, main="moving average")
```

d)
The moving average smoothes out a) a lot, while the oscillations cancel in b). c) looks more periodic.

# 1.20

a)

```{r}
w = rnorm(500,0,1)
(sample_acf <- acf(w, 20, plot=FALSE)$acf[20])
```
Estimated ACF = `r sample_acf`, actual ACF = 0


```{r}
w = rnorm(50,0,1)
(sample_acf <- acf(w, 20, plot=FALSE)$acf[20])
```
Now estimated ACF = `r sample_acf`

The higher n, the more closer the value will tent to the actual 0 value. With 50 vs 500, the difference doesn't seem that big however, as n = 50 sometimes is closer to 0 depending on time series realization